In [1]:
from sklearn import datasets

#importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline


In [2]:
iris=datasets.load_iris()
X=iris.data
y=iris.target

In [66]:
pd.DataFrame(X,columns=iris.feature_names)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=123,test_size=0.3,stratify=y)

In [4]:
from sklearn.svm import SVC

In [5]:
svc=SVC()

In [6]:
svc.fit(X_train,y_train)

SVC()

In [7]:
y_pred=svc.predict(X_test)

In [8]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [9]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.87      0.93        15
           2       0.88      1.00      0.94        15

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45



# Hyper parameter tuning

In [11]:
param={'kernel':['linear','poly','rbf']
    
}

In [12]:
from sklearn.model_selection import GridSearchCV


In [13]:
gsv= GridSearchCV(estimator=svc,
                 param_grid=param,
                 scoring='accuracy',verbose=-1
                 )

In [14]:
gsv


GridSearchCV(estimator=SVC(), param_grid={'kernel': ['linear', 'poly', 'rbf']},
             scoring='accuracy', verbose=-1)

In [45]:
gsv.fit(X_train,y_train)

GridSearchCV(estimator=SVC(), param_grid={'kernel': ['linear', 'poly', 'rbf']},
             scoring='accuracy', verbose=-1)

In [43]:
gsv.best_params_

{'kernel': 'rbf'}

In [17]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
pred=gsv.predict(X_test)

In [18]:
print(confusion_matrix(y_test,pred))

[[15  0  0]
 [ 0 13  2]
 [ 0  0 15]]


In [19]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.87      0.93        15
           2       0.88      1.00      0.94        15

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45



# Deploy


In [39]:
import pickle

In [47]:
filename='trained_model.sav'
pickle.dump(gsv,open(filename,'wb'))

# loading the saved model

In [60]:
load_model=pickle.load(open('trained_model.sav','rb'))

In [62]:
load_model

GridSearchCV(estimator=SVC(), param_grid={'kernel': ['linear', 'poly', 'rbf']},
             scoring='accuracy', verbose=-1)